"""add address column

Revision ID: 9b973edd986e
Revises: eaf898105887
Create Date: 2026-06-23 15:47:23.300713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b973edd986e'
down_revision: Union[str, Sequence[str], None] = 'eaf898105887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
