"""add review

Revision ID: f52dda889cc5
Revises: a341c822186a
Create Date: 2026-07-26 03:05:24.876084

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52dda889cc5'
down_revision: Union[str, Sequence[str], None] = 'a341c822186a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('review', sa.Column('shipment_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'review', 'shipment', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'shipment_id')
    op.drop_column('review', 'comment')
    op.drop_column('review', 'rating')
    # ### end Alembic commands ###
